package me.evgeniyosipov.jlchat.view;

import me.evgeniyosipov.jlchat.controller.JLChatController;
import me.evgeniyosipov.jlchat.model.JLChatModel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Evgeniy Osipov (osipoveg1990@gmail.com, http://evgeniyosipov.me)
 * @version 1.0
 */
public class JLChatView extends javax.swing.JFrame {

    /**
     * Creates new form JLChat
     */
    public JLChatView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JLChat");

        jTextField1.setText("admin");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Your Name");

        jTextField2.setText("localhost");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel2.setText("Server's IP");

        jTextField3.setText("1777");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel3.setText("Server's Port");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Send");
        jButton3.setToolTipText("");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Instructions:\n\n1) Create a server (you can just click the \"Connect\")\n\n2) Connect to the server (only one client can connect to the server):\n\na) Enter in the \"Your Name\" you name\nb) Enter in the \"IP Server\" host's address (for example, 192.168.0.111)\nc) Enter in the \"Server Port\" host's port\nd) Choose \"Client\" in \"Connect as\"\ne) Press the \"Connect\"\n\n3) Chat =)\n\n4) Uncouple connection to both sides and then repeat steps 1-3 to restore the connection\n\nPleasant conversation!");
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Server");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioButton2.setText("Client");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel4.setText("Connect as");

        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Disconnect");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Information");

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getjButton1().setEnabled(false);
        getjButton2().setEnabled(true);

        getjRadioButton1().setEnabled(false);
        getjRadioButton2().setEnabled(false);

        getjTextField1().setEnabled(false);
        getjTextField2().setEnabled(false);
        getjTextField3().setEnabled(false);

        JLChatModel.setUserName(getjTextField1().getText());
        JLChatModel.setServerIP(getjTextField2().getText());
        JLChatModel.setServerPort(Integer.parseInt(getjTextField3().getText()));

        JLChatModel.setBegin(true);
        JLChatModel.setConnect(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getjButton1().setEnabled(true);
        getjButton2().setEnabled(false);
        getjButton3().setEnabled(false);

        getjRadioButton1().setEnabled(true);
        getjRadioButton2().setEnabled(true);

        getjTextField1().setEnabled(true);
        getjTextField2().setEnabled(true);
        getjTextField3().setEnabled(true);

        getjTextArea2().setEnabled(false);

        JLChatModel.setBegin(false);
        JLChatModel.setConnect(false);

        if (getjRadioButton1().isSelected()) {
            try {
                if (JLChatModel.getBr() != null && JLChatModel.getBw() != null) {
                    JLChatModel.getBr().close();
                    JLChatModel.getBw().flush();
                    JLChatModel.getBw().close();
                }
                if (JLChatModel.getSocket() != null) {
                    JLChatModel.getSocket().close();
                }

                JLChatModel.getServerSocket().close();

                JLChatModel.setBr(null);
                JLChatModel.setBw(null);
                JLChatModel.setSocket(null);
                JLChatModel.setServerSocket(null);
            } catch (IOException ex) {
                Logger.getLogger(JLChatView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                if (JLChatModel.getBr() != null && JLChatModel.getBw() != null) {
                    JLChatModel.getBr().close();
                    JLChatModel.getBw().flush();
                    JLChatModel.getBw().close();
                }
                if (JLChatModel.getSocket() != null) {
                    JLChatModel.getSocket().close();
                }

                JLChatModel.setBr(null);
                JLChatModel.setBw(null);
                JLChatModel.setSocket(null);
            } catch (IOException ex) {
                Logger.getLogger(JLChatView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JLChatModel.setSafeChatString(getjTextArea2().getText());
        JLChatController.sendMessageMethod(JLChatModel.getSafeChatString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showConfirmDialog(
                null,
                "JLChat v1.0 \n"
                + "Evgeniy Osipov, 2013 \n"
                + "osipoveg1990@gmail.com, http://evgeniyosipov.me \n\n",
                "About", JOptionPane.PLAIN_MESSAGE,
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        JLChatView jlch = new JLChatView();
        jlch.setVisible(true);

        while (true) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(JLChatView.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (JLChatModel.isBegin()) {

                if (getjRadioButton1().isSelected()) {
                    JLChatController.startServerSockets();

                } else if (getjRadioButton2().isSelected()) {
                    JLChatController.startClientSockets();

                }
            }

            if (JLChatModel.isConnect()) {
                try {
                    if (JLChatModel.getSendMessage().length() != 0) {
                        JLChatController.sendMessageSafe();
                    }

                    if (JLChatModel.getBr().ready()) {
                        JLChatController.chatMessageSafe();
                    }

                } catch (IOException ex) {
                    Logger.getLogger(JLChatView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }

    /**
     * @return the buttonGroup1
     */
    public static javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    /**
     * @param aButtonGroup1 the buttonGroup1 to set
     */
    public static void setButtonGroup1(javax.swing.ButtonGroup aButtonGroup1) {
        buttonGroup1 = aButtonGroup1;
    }

    /**
     * @return the jButton1
     */
    public static javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param ajButton1 the jButton1 to set
     */
    public static void setjButton1(javax.swing.JButton ajButton1) {
        jButton1 = ajButton1;
    }

    /**
     * @return the jButton2
     */
    public static javax.swing.JButton getjButton2() {
        return jButton2;
    }

    /**
     * @param ajButton2 the jButton2 to set
     */
    public static void setjButton2(javax.swing.JButton ajButton2) {
        jButton2 = ajButton2;
    }

    /**
     * @return the jButton3
     */
    public static javax.swing.JButton getjButton3() {
        return jButton3;
    }

    /**
     * @param ajButton3 the jButton3 to set
     */
    public static void setjButton3(javax.swing.JButton ajButton3) {
        jButton3 = ajButton3;
    }

    /**
     * @return the jLabel1
     */
    public static javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param ajLabel1 the jLabel1 to set
     */
    public static void setjLabel1(javax.swing.JLabel ajLabel1) {
        jLabel1 = ajLabel1;
    }

    /**
     * @return the jLabel2
     */
    public static javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param ajLabel2 the jLabel2 to set
     */
    public static void setjLabel2(javax.swing.JLabel ajLabel2) {
        jLabel2 = ajLabel2;
    }

    /**
     * @return the jLabel3
     */
    public static javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param ajLabel3 the jLabel3 to set
     */
    public static void setjLabel3(javax.swing.JLabel ajLabel3) {
        jLabel3 = ajLabel3;
    }

    /**
     * @return the jLabel4
     */
    public static javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param ajLabel4 the jLabel4 to set
     */
    public static void setjLabel4(javax.swing.JLabel ajLabel4) {
        jLabel4 = ajLabel4;
    }

    /**
     * @return the jMenu1
     */
    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     * @param jMenu1 the jMenu1 to set
     */
    public void setjMenu1(javax.swing.JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    /**
     * @return the jMenu2
     */
    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     * @param jMenu2 the jMenu2 to set
     */
    public void setjMenu2(javax.swing.JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    /**
     * @return the jMenuBar1
     */
    public static javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param ajMenuBar1 the jMenuBar1 to set
     */
    public static void setjMenuBar1(javax.swing.JMenuBar ajMenuBar1) {
        jMenuBar1 = ajMenuBar1;
    }

    /**
     * @return the jMenuItem1
     */
    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     * @param jMenuItem1 the jMenuItem1 to set
     */
    public void setjMenuItem1(javax.swing.JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    /**
     * @return the jMenuItem3
     */
    public javax.swing.JMenuItem getjMenuItem3() {
        return jMenuItem3;
    }

    /**
     * @param jMenuItem3 the jMenuItem3 to set
     */
    public void setjMenuItem3(javax.swing.JMenuItem jMenuItem3) {
        this.jMenuItem3 = jMenuItem3;
    }

    /**
     * @return the jRadioButton1
     */
    public static javax.swing.JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    /**
     * @param ajRadioButton1 the jRadioButton1 to set
     */
    public static void setjRadioButton1(javax.swing.JRadioButton ajRadioButton1) {
        jRadioButton1 = ajRadioButton1;
    }

    /**
     * @return the jRadioButton2
     */
    public static javax.swing.JRadioButton getjRadioButton2() {
        return jRadioButton2;
    }

    /**
     * @param ajRadioButton2 the jRadioButton2 to set
     */
    public static void setjRadioButton2(javax.swing.JRadioButton ajRadioButton2) {
        jRadioButton2 = ajRadioButton2;
    }

    /**
     * @return the jScrollPane1
     */
    public static javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param ajScrollPane1 the jScrollPane1 to set
     */
    public static void setjScrollPane1(javax.swing.JScrollPane ajScrollPane1) {
        jScrollPane1 = ajScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public static javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param ajScrollPane2 the jScrollPane2 to set
     */
    public static void setjScrollPane2(javax.swing.JScrollPane ajScrollPane2) {
        jScrollPane2 = ajScrollPane2;
    }

    /**
     * @return the jScrollPane3
     */
    public static javax.swing.JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    /**
     * @param ajScrollPane3 the jScrollPane3 to set
     */
    public static void setjScrollPane3(javax.swing.JScrollPane ajScrollPane3) {
        jScrollPane3 = ajScrollPane3;
    }

    /**
     * @return the jTextArea1
     */
    public static javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }

    /**
     * @param ajTextArea1 the jTextArea1 to set
     */
    public static void setjTextArea1(javax.swing.JTextArea ajTextArea1) {
        jTextArea1 = ajTextArea1;
    }

    /**
     * @return the jTextArea2
     */
    public static javax.swing.JTextArea getjTextArea2() {
        return jTextArea2;
    }

    /**
     * @param ajTextArea2 the jTextArea2 to set
     */
    public static void setjTextArea2(javax.swing.JTextArea ajTextArea2) {
        jTextArea2 = ajTextArea2;
    }

    /**
     * @return the jTextArea3
     */
    public static javax.swing.JTextArea getjTextArea3() {
        return jTextArea3;
    }

    /**
     * @param ajTextArea3 the jTextArea3 to set
     */
    public static void setjTextArea3(javax.swing.JTextArea ajTextArea3) {
        jTextArea3 = ajTextArea3;
    }

    /**
     * @return the jTextField1
     */
    public static javax.swing.JTextField getjTextField1() {
        return jTextField1;
    }

    /**
     * @param ajTextField1 the jTextField1 to set
     */
    public static void setjTextField1(javax.swing.JTextField ajTextField1) {
        jTextField1 = ajTextField1;
    }

    /**
     * @return the jTextField2
     */
    public static javax.swing.JTextField getjTextField2() {
        return jTextField2;
    }

    /**
     * @param ajTextField2 the jTextField2 to set
     */
    public static void setjTextField2(javax.swing.JTextField ajTextField2) {
        jTextField2 = ajTextField2;
    }

    /**
     * @return the jTextField3
     */
    public static javax.swing.JTextField getjTextField3() {
        return jTextField3;
    }

    /**
     * @param ajTextField3 the jTextField3 to set
     */
    public static void setjTextField3(javax.swing.JTextField ajTextField3) {
        jTextField3 = ajTextField3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private static javax.swing.JRadioButton jRadioButton1;
    private static javax.swing.JRadioButton jRadioButton2;
    private static javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextArea jTextArea2;
    private static javax.swing.JTextArea jTextArea3;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JTextField jTextField2;
    private static javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
